USE votemeup;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE user_status;
LOAD DATA LOCAL INFILE "Data\\user_status" INTO TABLE user_status
FIELDS TERMINATED BY ';;' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

TRUNCATE TABLE country;
LOAD DATA LOCAL INFILE "Data\\country" INTO TABLE country
FIELDS TERMINATED BY ';;' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

TRUNCATE TABLE region;
LOAD DATA LOCAL INFILE "Data\\region" INTO TABLE region
FIELDS TERMINATED BY ';;' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

TRUNCATE TABLE city;
LOAD DATA LOCAL INFILE "Data\\city" INTO TABLE city
FIELDS TERMINATED BY ';;' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

TRUNCATE TABLE district;
LOAD DATA LOCAL INFILE "Data\\district" INTO TABLE district
FIELDS TERMINATED BY ';;' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

TRUNCATE TABLE proposal_status;
LOAD DATA LOCAL INFILE "Data\\proposal_status" INTO TABLE proposal_status
FIELDS TERMINATED BY ';;' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

TRUNCATE TABLE proposal_level;
LOAD DATA LOCAL INFILE "Data\\proposal_level" INTO TABLE proposal_level
FIELDS TERMINATED BY ';;' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

TRUNCATE TABLE role;
LOAD DATA LOCAL INFILE "Data\\role" INTO TABLE role
FIELDS TERMINATED BY ';;' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

TRUNCATE TABLE userd;
LOAD DATA LOCAL INFILE "Data\\userd" INTO TABLE userd
FIELDS TERMINATED BY ';;' LINES TERMINATED BY '\r\n' IGNORE 2 LINES;

TRUNCATE TABLE proposal;
LOAD DATA LOCAL INFILE "Data\\proposal" INTO TABLE proposal
FIELDS TERMINATED BY ';;' LINES TERMINATED BY '\r\n' IGNORE 2 LINES;

TRUNCATE TABLE category;
LOAD DATA LOCAL INFILE "Data\\category" INTO TABLE category
FIELDS TERMINATED BY ';;' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

TRUNCATE TABLE document;
LOAD DATA LOCAL INFILE "Data\\document" INTO TABLE document
FIELDS TERMINATED BY ';;' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

TRUNCATE TABLE vote;
LOAD DATA LOCAL INFILE "Data\\vote" INTO TABLE vote
FIELDS TERMINATED BY ';;' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

TRUNCATE TABLE commentd;
LOAD DATA LOCAL INFILE "Data\\commentd" INTO TABLE commentd
FIELDS TERMINATED BY ';;' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

TRUNCATE TABLE proposal_category;
LOAD DATA LOCAL INFILE "Data\\proposal_category" INTO TABLE proposal_category
FIELDS TERMINATED BY ';;' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

SET FOREIGN_KEY_CHECKS = 1;